name: Deploy V2Ray

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Run local install script
      run: |
        chmod +x ./install.sh
        ./install.sh
